# 1.	Import du package : 

In [1]:
import numpy as np

# 2-Creer des donnees  

## 2.1-Creer un numpy array a partir d'une liste/d'une liste de liste(matrice)

In [2]:
tab1=np.array([1,2,3,4,5,0,-5,-7,-8])
tab2=np.array([[1,2],[2,3]])
tab3=np.array([[[1,2],[3,4],],[[0,2],[0,5]],[[0,1],[2,9]]])

In [3]:
tab2

array([[1, 2],
       [2, 3]])

## 2.2 Creer un numpy array a partir des fonction predefinies

In [4]:
zero=np.zeros((3,3)) # matrice de zero
one=np.ones((3,3))     #matrice de un
eye=np.eye(6)          # matrice identite

In [5]:
eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [6]:
# creer une liste avec np.arange(debut , fin -1, pas )
array_arrange=np.arange(1,11,1)
array_arrange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# creer une liste avec np.linspace(debut , fin, nombre d'element)
np.linspace(0,2,5) # tres utile pour les graphiques

array([0. , 0.5, 1. , 1.5, 2. ])

In [8]:
# creer un numpy array de nombres aleatoires np.random.random(shape)
np.random.random((4,2)) # utile pour initialiser les poids dans les reseaux de neurones

array([[0.68070562, 0.92902605],
       [0.54320884, 0.03900335],
       [0.42323783, 0.26066206],
       [0.51762241, 0.73342722]])

# 3-Fonctions mathematiques et statistiques avec numpy

In [9]:
# fonctions mathematiques basiques
tab_sum=np.sum(tab1)
tab_mean=np.mean(tab1)
tab_min=np.min(tab1)
tab_max=np.max(tab1)
tab_std=np.std(tab1)
tab_sqrt=np.sqrt(tab1)
tab_abs=np.abs(tab1)
tab_power=np.power(tab1,3)
tab_exp=np.exp(tab1)
tab_log=np.log(tab1)
tab_median=np.median(tab1)
tab_median

/tmp/ipykernel_18/3042533463.py:7: RuntimeWarning: invalid value encountered in sqrt
  tab_sqrt=np.sqrt(tab1)
/tmp/ipykernel_18/3042533463.py:11: RuntimeWarning: divide by zero encountered in log
  tab_log=np.log(tab1)
/tmp/ipykernel_18/3042533463.py:11: RuntimeWarning: invalid value encountered in log
  tab_log=np.log(tab1)


1.0

# 4-manipulation des matrice avec numpy

In [10]:
# Produit matriciel
matrice=[[1,0,3],[2,2,8]]
matrice_p= np.dot(tab2,matrice)
matrice_p

array([[ 5,  4, 19],
       [ 8,  6, 30]])

In [11]:
# transpose
np.transpose(matrice_p)

array([[ 5,  8],
       [ 4,  6],
       [19, 30]])

In [12]:
# inverse matrice (pour les matrice carrees non singulieres)
np.linalg.inv(tab2)

array([[-3.,  2.],
       [ 2., -1.]])

In [13]:
 # determinant
np.linalg.det(eye)

1.0

# 5- Acceder aux elements,modifier,selectionner et mettre a jour un numpy array 

In [14]:
# acceder
tab1[2]

3

In [15]:
tab1[2]=7
tab1[2]

7

In [16]:
# selectionner un element qui respecte une condition
tab1[tab1>2]

array([7, 4, 5])

In [17]:
#indice des elements respectant la condition 
np.where(tab1>2)

(array([2, 3, 4]),)

In [18]:
# slicing et indexation avancee
#slicing
tab2[0,:]

array([1, 2])

In [19]:
tab2[:,0]

array([1, 2])

In [20]:
#indexation avancee
tab2[[0,1,1],[1,1,0]]

array([2, 3, 2])

In [21]:
# addition
ar1=np.array([1,2,3])
ar2=np.array([4,5,3])
ar1+ar2

array([5, 7, 6])

In [22]:
# multiplication
ar1*ar2

array([ 4, 10,  9])

In [23]:
ar3=np.array([[1,2,3],[4,2,7]])
ar3+np.array([1,1,1])

array([[2, 3, 4],
       [5, 3, 8]])

In [24]:
ar4=np.arange(9)
ar4
ar4.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
#ajouter un element dans une matrice
np.append(tab1,[0,6,9])

array([ 1,  2,  7,  4,  5,  0, -5, -7, -8,  0,  6,  9])

In [26]:
#connaitre le type d'un objet 
ar3.dtype

dtype('int64')